---
title: "02-gastrula-exp"
output: html_document
---

```{r}
library(tidyverse)
```
```{r}
gast <- read.delim("https://github.com/RobertsLab/project-sc-RNAseq/files/9162857/gastrula_geneBYcellsexpressed.txt", sep = "\t")
```

```{r}
ggplot() +
  geom_histogram(data = gast, aes(x = num_cells_expressed), fill = "blue", alpha = 0.2, bins = 50)
```


```{r}
gast$gp <- cut(gast$num_cells_expressed, breaks=3, include.lowest=FALSE)
ggplot(gast, aes(gp, fill=gp)) + geom_bar()
```
Lets count based on number of cells expressed in ..


```{r}
nrow(filter(gast, num_cells_expressed == 0))
```

```{r}
nrow(filter(gast, num_cells_expressed > 5))
```


```{r}
nrow(filter(gast, num_cells_expressed <= 5))
```

```{r}
nrow(filter(gast, num_cells_expressed > 5 , num_cells_expressed <= 1000))
```
```{r}
nrow(filter(gast, num_cells_expressed > 5 , num_cells_expressed <= 10))
```


```{r}
nrow(filter(gast, num_cells_expressed > 1000 , num_cells_expressed < 20000))
```

```{r}
nrow(filter(gast, num_cells_expressed > 16000))
```

```{r}
hix <- filter(gast, num_cells_expressed > 16000) %>%
  select(id)

write_delim(hix, "../output/hix.tab")
```



HOW MANY genes are labelled as uncharacterized


```{r}
library(stringr)
```

```{r}
gast
```


```{r}
gast %>%
  dplyr::filter(str_detect(gene_short_name, "unchar"))
```

Of 38222 genes, 18301 are uncharacterized.

```{r}
gast %>%
  dplyr::filter(num_cells_expressed == 0, !str_detect(gene_short_name, "unchar"))
```

```{r}
nrow(dplyr::filter(gast, num_cells_expressed == 0, !str_detect(gene_short_name, "unchar")))
```



```{r}
nrow(dplyr::filter(gast, num_cells_expressed > 5, !str_detect(gene_short_name, "unchar")))
```


```{r}
nrow(dplyr::filter(gast, num_cells_expressed <= 5, !str_detect(gene_short_name, "unchar")))
```

```{r}
nrow(dplyr::filter(gast, num_cells_expressed > 5 , num_cells_expressed <= 1000, !str_detect(gene_short_name, "unchar")))
```
```{r}
nrow(dplyr::filter(gast, num_cells_expressed > 5 , num_cells_expressed <= 10, !str_detect(gene_short_name, "unchar")))
```


```{r}
nrow(dplyr::filter(gast, num_cells_expressed > 1000 , num_cells_expressed < 20000, !str_detect(gene_short_name, "unchar")))
```

```{r}
nrow(dplyr::filter(gast, num_cells_expressed > 16000, !str_detect(gene_short_name, "unchar")))
```


Can we plot each category of uncharacter vs annotated.

```{r}
gast %>%
  mutate(annot = case_when(
    startsWith(gene_short_name, "uncharac") ~ "unchar",
    endsWith(gene_short_name, "S") ~ "Sick"
    ))
```


```{r}
gg <- gast %>%
  dplyr::mutate(annotation = ifelse(grepl("uncharac", gene_short_name), 'unchar', 'annot')) %>%
  dplyr::mutate(level = ifelse(num_cells_expressed %in% 5:1000, "low",
                                     ifelse(num_cells_expressed %in% 1001:10000, "medium",
                                            ifelse(num_cells_expressed %in% 10001:20000, "high", "none"))))
```


```{r}
library(tidyverse)
```

```{r}
ggplot(gg, aes(x=num_cells_expressed)) + 
    geom_histogram() +
    facet_grid(~annotation)
```

```{r}
ggplot(gg, aes(x=num_cells_expressed)) + 
    geom_histogram() +
    facet_grid(~level)
```
```{r}
gg$level <- factor(gg$level,levels = c("none", "low", "medium", "high"))
```



```{r}
ggplot(gg, aes(x = level, fill = annotation)) + 
  geom_bar()
```




```{r}
ggplot(gg, aes(x = annotation, fill = level)) + 
  geom_bar()
```



```{r}

```


